### ISSUE TITLE
dliobenchmark installation issue.kindly help 

### ISSUE THREAD

**Issue by shubh0155** [argonne-lcf/dlio_benchmark#105]
I have installed and tested dlio benchmark on my cluster previously but from last three days there are some errors which i am facing on my system regarding openfabrics and i am unable to diagnose the cause. I even tried installing it on other system but same issue is coming again and again . Any kind of help and suggestions will help me a lot . i have attached the screenshot for reference. please help

![Screenshot (5)](https://github.com/argonne-lcf/dlio_benchmark/assets/121078956/5f2f20bb-b180-40ed-89d2-77604b7eec89)

**Comment by zhenghh04** [comment]
@shubh0155 , this looks like related to MPI. Try uninstall mpi4py and reinstall it.

**Comment by shubh0155** [comment]
@zhenghh04 thank you for the help. after reinstalling and running the benchmark its not giving any error but its not starting to run the epochs also its creating the folder in hydra_log but the file is empty from inside. I even reinstalled the dlio again and the same challange i am facing again and again.

**Comment by shubh0155** [comment]
@zhenghh04  Thank you for your assistance! It appears that there have been some changes in the Dlio config files, and now the benchmarking process is running in the background. However, I'm encountering an issue where the Darshan logs are not being generated as expected. The size of my Darshan logs is 72KB, but the "test.darshan" file ends up being much larger, at 3.4MB. I need to diagnose and address this issue. If you've encountered a similar challenge in the past and have any insights or solutions, I would greatly appreciate your input. please note that the Dlio-benchmark issue has been resolved; it was related to an MPI error. Thanks again for your help!

**Comment by hariharan-devarajan** [comment]
@shubh0155 check #107 issue, i have a set of steps here that can help you profile. Darshan has some issues with Ai based workload so we have our own profiler for AI.

**Comment by hariharan-devarajan** [comment]
@shubh0155 did u try our profiler and have any success?

**Comment by hariharan-devarajan** [comment]
@shubh0155 because this was originally an MPI issue. I will close this. Let us know if you cannot get profiling logs using dlio profiler
