### ISSUE TITLE
output_folder doesn't get created if storage class is S3

### ISSUE THREAD

**Issue by krehm** [argonne-lcf/dlio_benchmark#125]
While experimenting with S3 storage, I found that the output_folder doesn't get created.  This happened because the code tries to create the output folder with the following code:
```
        self.output_folder = self.args.output_folder
       self.output = StorageFactory().get_storage(self.args.storage_type, self.args.output_folder,
                                                  self.args.framework)
       self.output.create_namespace(exist_ok=True)
```
but that assumes that the storage class is posix.  If the class is S3, then self.output.create_namespace() is called with what should be a bucket, and the routine itself is a no-op because the bucket is supposed to already exist.   Log files are always posix, so I've created pull request #124 where I've replaced the above calls with an os.makedirs() call which always works for posix directories.  

Separately, I moved the configuration of the dlio.log file farther down after the prior dlio.log has been deleted, so there is no chance that a process will end up with a log handler pointing to an open but unlinked file.

Finally, there was one log message that was issued before the prior dlio.log was deleted, so the message was lost, I moved it later in the code so that it gets logged.

**Comment by zhenghh04** [comment]
Thank you @krehm. We will review the PR and let you know.

**Comment by krehm** [comment]
Sorry about missing the self.output_folder reference, not sure why I didn't hit that myself...

**Comment by krehm** [comment]
PR has been merged
