### ISSUE TITLE
unet3d training fails when used with multiprocessing_context=spawn

### ISSUE THREAD

**Issue by krehm** [argonne-lcf/dlio_benchmark#140]
I have been chasing a problem where the unet3d training run fails at the end with a malloc corruption abort.   I have managed to shrink the size of the training run down to the minimum that fails, which is 5 sample files and 1 MPI process and 1 reader process.   The training run reaches the end and calculates the AU efficiency, then aborts.
```
...
INFO] Averaged metric over all epochs
[METRIC] ==========================================================
[METRIC] Training Accelerator Utilization [AU] (%): 0.0000 (0.0000)
[METRIC] Training Throughput (samples/second): 0.4132 (0.0000)
[METRIC] Training I/O Throughput (MB/second): 57.7696 (0.0000)
[METRIC] train_au_meet_expectation: fail
[METRIC] ==========================================================
 [/mnt/nvm/rehm/storage/dlio_benchmark/dlio_benchmark/utils/statscounter.py:121]
[INFO] 2024-01-23T08:49:04.125469 outputs saved in RANKID_output.json [/mnt/nvm/rehm/storage/dlio_benchmark/dlio_benchmark/utils/statscounter.py:318]
[DLIO_PROFILER ERROR]: signal caught 15
[DLIO_PROFILER ERROR]: signal caught 15
[DLIO_PROFILER ERROR]: signal caught 11
malloc(): unsorted double linked list corrupted
[DLIO_PROFILER ERROR]: signal caught 6
```
The two signal 15 messages correspond to the resource_tracker child process and the single child process spawned to read the 5 sample files.  What happens is that one of the threads in the spawn-child aborts due to the malloc corruption.   numpy is running BLAS and has a thread pool with a number of threads in it.  After the one thread takes the abort, all the other threads are left blocked waiting for pthread locks forever, and the resource_tracker child process waits for the spawn-child to exit, which it never will.   Both processes have to be killed off with "kill -9" to get rid of them.   I do not yet know the source of the signal 11 seen above, perhaps it is also related to the malloc corruption.

I will upload the yaml file that I use with this run.   You will note that profiling is disabled, yet it appears to be running anyway in both child processes.     I am running the latest 'main' branch, commit fb762c286f448b439fd230a7a79e5a57b9efa11d is the head commit.

The command line that I use is:
```
mpirun -np 1 python3 dlio_benchmark/dlio_benchmark/main.py --config-path=/mnt/nvm/rehm/storage/storage-conf workload=unet3d ++workload.workflow.train=True ++hydra.output_subdir=configs
```
[unet3d.yaml.txt](https://github.com/argonne-lcf/dlio_benchmark/files/14025738/unet3d.yaml.txt)

**Comment by krehm** [comment]
For dlio_profiler I am using the dev branch.  I just did a git pull and then re-installed, I see some new changes, now using 0.0.3, but the same problem still occurs.

**Comment by krehm** [comment]
I modified dlio_profiler, removing the signal-catching of SIGTERM, and the training run now completes successfully.   Perhaps numpy/blas has its own signal-handling code, and the dlio_profiler signal handling is interfering with it?
```
(venv) [root@delphi-029 dlio-profiler]# git diff src/dlio_profiler/utils/utils.h
diff --git a/src/dlio_profiler/utils/utils.h b/src/dlio_profiler/utils/utils.h
index 9170b53..5dddaec 100644
--- a/src/dlio_profiler/utils/utils.h
+++ b/src/dlio_profiler/utils/utils.h
@@ -60,7 +60,9 @@ inline void set_signal() {
   sigaction(SIGUSR1, &sa, NULL);
   sigaction(SIGABRT, &sa, NULL);
   sigaction(SIGHUP, &sa, NULL);
+/*
   sigaction(SIGTERM, &sa, NULL);
+*/
   sigaction(SIGINT, &sa, NULL);
 }  // GCOVR_EXCL_STOP

```

**Comment by krehm** [comment]
Also, I don't think it makes sense for the profiler to be running in the resource_tracker child process even if the profiler is configured.

**Comment by krehm** [comment]
It works, thanks!   And thanks for the MPI.finalize fix as well, I was just getting ready to start working on that.

**Comment by krehm** [comment]
I suspect there may still be a problem with numpy itself, as when I run a larger benchmark, I see this message a lot:
```
terminate called without an active exception
```
which implies that a BLAS thread is exiting without having been joined by the thread scheduler.  Perhaps the numpy/BLAS thread scheduler is not catching signals like 15, telling its threads to finish up, joining them, and then finally exiting.

Do you guys see this message as well?

**Comment by hariharan-devarajan** [comment]
Yes i saw this in one of my profiler runs but didn't yet get time why numpy does that yet.

**Comment by hariharan-devarajan** [comment]
@krehm If this issue is solved. Let me know I can close it.

**Comment by krehm** [comment]
@hariharan-devarajan this can be closed.
