### ISSUE TITLE
Checkpointing issues

### ISSUE THREAD

**Issue by johnugeorge** [argonne-lcf/dlio_benchmark#15]
I had a quick test with Checkpointing feature. I see the following issues

1. When `epochs_between_checkpoints` is set,  evaluation is skipped in the same epoch where checkpointing happens.
2. when `steps_between_checkpoints` is set,  error occurs during checkpointing of second block

```
Traceback (most recent call last):
  File "dlio_benchmark/src/dlio_benchmark.py", line 354, in main
    benchmark.run()
  File "dlio_benchmark/src/dlio_benchmark.py", line 295, in run
    steps = self._train(epoch)
  File "dlio_benchmark/src/dlio_benchmark.py", line 236, in _train
    self.stats.end_block(epoch, block, block_step)
  File "/home/ubuntu/storage/dlio_benchmark/src/utils/statscounter.py", line 103, in end_block
    if 'end' in self.per_epoch_stats[epoch][f'block{block}']:
KeyError: 'block2' 
```

**Comment by zhenghh04** [comment]
Thanks for testing. I'll fix that later today.

**Comment by zhenghh04** [comment]
@johnugeorge I fixed issue for 2, please check it again. 

For 1, evaluation is independent of checkpointing, please double check and confirm again whether you still have that issue. It didn't show on my side.

**Comment by johnugeorge** [comment]
Thanks @zhenghh04 I tried it and I didn't see any issues
