### ISSUE TITLE
TensorFlow Training Array Out Of Bounds Exception Error 

### ISSUE THREAD

**Issue by TheAssembler1** [argonne-lcf/dlio_benchmark#151]
Found the bug when trying to run the unet3d workload with the TensorFlow framework. Previously, the bug did not show up because PyTorch uses the `ConfigArguments.get_global_map_index` method, which distributes the batches differently than the `ConfigArguments.build_sample_map_iter`. The error can be reproduced by changing the unet3d workload framework to TensorFlow and running the training with `mpirun -np 12 dlio_benchmark workload=unet3d ++workload.workflow.generate_data=True ++workload.workflow.train=True`.

**The error occurs on these lines:**

https://github.com/argonne-lcf/dlio_benchmark/blob/99d3fb0863983b0681ddca612978e05824bb6833/dlio_benchmark/utils/config.py#L330-L333

**Here is why the error occurs:**

The following line gets the number of samples per thread. It is not rounded, so with 12 MPI processes and 4 read threads per process, the samples per thread is `168 / 12 / 4 = 3.5`. This is set to `self.samples_per_thread` here:

https://github.com/argonne-lcf/dlio_benchmark/blob/99d3fb0863983b0681ddca612978e05824bb6833/dlio_benchmark/utils/config.py#L311

Once the number of samples per thread is generated, the code iterates through all the threads, adding `self.num_samples_per_thread` samples at each iteration. The issue is that the loop uses an integer to check whether the `self.samples_per_thread` has been completed. Since, in our case, the `self.samples_per_thread = 3.5` it will add 4 samples to every thread. However, there are only 168 files available with one sample a file. So that is why we get the array out of bounds exception: `samples_per_thread * num_ranks * num_threads = 4  * 12 * 4 > 168`. This code can be seen below

https://github.com/argonne-lcf/dlio_benchmark/blob/99d3fb0863983b0681ddca612978e05824bb6833/dlio_benchmark/utils/config.py#L322-L340

**Comment by hariharan-devarajan** [comment]
@TheAssembler1 I see two potential fixes for this. Generally the dataset should be divisible by the number of GPUs * number of workers * batch size. If this is not true then apps can do two things
1. Read less number of samples. That is do a math.floor and read only 3 instead of 3.5
2. Or change the num GPU * workers* batchsize to be a multiple.

Does this makes sense @zhenghh04 @TheAssembler1 ?

**Comment by hariharan-devarajan** [comment]
@TheAssembler1 Can u check #152 and see if this solves your problem?

**Comment by TheAssembler1** [comment]
@hariharan-devarajan Yes, I checked #152 and that solved my problem. Thanks @hariharan-devarajan @zhenghh04 !

**Comment by zhenghh04** [comment]
thanks for confirmation @TheAssembler1. I'll close the issue now.
