### ISSUE TITLE
Sample Distribution Optimization

### ISSUE THREAD

**Issue by TheAssembler1** [argonne-lcf/dlio_benchmark#155]
I'm trying to run the Bert workload and the time it takes to reach the training loop is significant (around 10 minutes in my case with 64 mpi processes on a very fast HPC system). So, I profiled the bert workload (with a reduced total number of files for testing purposes) with a single process and found that the `os.path.abspath` is taking most of the time. This is used when distributing the samples. I profiled the bert workload when using both the Pytorch and TensorFlow frameworks using the `npz` file format because they differ in sample distribution methods `get_global_map_index` and `build_sample_map_iter` respectively. I stopped the profiling once the process hit the training loop. I used [py-spy](https://github.com/benfred/py-spy) to profile the processes.

Profile for `get_global_map_index`:
```
  %Own   %Total  OwnTime  TotalTime  Function (filename)                        
  0.00%   0.00%   38.52s    38.52s   normpath (posixpath.py)
  0.00%   0.00%   21.89s    81.53s   abspath (posixpath.py)
  0.00%   0.00%   15.03s    15.03s   __init__ (dlio_benchmark/data_loader/torch_
  0.00%   0.00%   13.97s    15.04s   join (posixpath.py)
  0.00%   0.00%   11.69s    93.22s   get_global_map_index (dlio_benchmark/utils/
```

Profile for `build_sample_map_iter`:
```
  %Own   %Total  OwnTime  TotalTime  Function (filename)                        
  0.00%   0.00%   40.64s    40.64s   normpath (posixpath.py)
  0.00%   0.00%   23.99s    88.22s   abspath (posixpath.py)
  0.00%   0.00%   20.86s    109.1s   build_sample_map_iter (dlio_benchmark/utils
  0.00%   0.00%   14.51s    15.86s   join (posixpath.py)
  0.00%   0.00%    5.67s     7.73s   isabs (posixpath.py)
```
The call to `abspath` is taking a considerable portion of the time for workloads that have a large sample size. This runtime could be improved by eliminating the redundant calls to `abspath`. Here is a commit with a fix that does this [commit](https://github.com/TheAssembler1/dlio_benchmark/commit/e5a34c8e9d45fa4724e355aed2204d4839532e91).

Here is my profiler results after the commit is applied.
Profile for `get_global_map_index`:
```
  %Own   %Total  OwnTime  TotalTime  Function (filename)                        
  0.00%   0.00%    5.63s     5.63s   get_global_map_index (dlio_benchmark/utils/
  0.00%   0.00%   0.300s    0.690s   _call_with_frames_removed (<frozen importli
  0.00%   0.00%   0.250s    0.250s   get_tensor (dlio_benchmark/checkpointing/py
  0.00%   0.00%   0.060s    0.640s   <module> (torch/__init__.py)
  0.00%   0.00%   0.050s    0.050s   __getattr__ (torch/_ops.py)
```

Profile for `build_sample_map_iter`:
```
  %Own   %Total  OwnTime  TotalTime  Function (filename)                        
  0.00%   0.00%   11.90s    11.90s   build_sample_map_iter (dlio_benchmark/utils
  0.00%   0.00%   0.000s    11.90s   _run_app (hydra/_internal/utils.py)
  0.00%   0.00%   0.000s    11.90s   run_job (hydra/core/utils.py)
  0.00%   0.00%   0.000s    11.90s   <module> (dlio_benchmark/main.py)
  0.00%   0.00%   0.000s    11.90s   run_and_report (hydra/_internal/utils.py)
```

As can be seen the `abspath` method is no longer in the top 5 methods of the runtime and the time to get to the training loop is reduced significantly.

**Comment by zhenghh04** [comment]
@TheAssembler1 would you mind sending a PR? And we will take a look from there.

**Comment by zhenghh04** [comment]
Thanks for the fix @TheAssembler1
