### ISSUE TITLE
multiple GPUs accessing the same part of the dataset

### ISSUE THREAD

**Issue by yxkyong** [argonne-lcf/dlio_benchmark#160]
We find that multiple GPUs are accessing the same part of the dataset while testing the MLPerf Benchmark v1.0. 

- Our environment:

**mlperf storage v1.0-branch** (https://github.com/mlcommons/storage/tree/v1.0-branch )
**dlio_benchmark @99d3b0** (https://github.com/argonne-lcf/dlio_benchmark/tree/99d3fb0863983b0681ddca612978e05824bb6833, mlperf storage v1.0-branch reference)

- Experimental settings:
   workload: unet3d
   num_files_train: 500
   read_threads: 1
   test command:
   `./benchmark.sh run --hosts x.x.x.x --workload unet3d --accelerator-type h100 --num-accelerators 10 --results-dir /result --param dataset.num_files_train=500 --param dataset.data_folder=/data 
`

- Result:
We added the output of access information in reader_handle.py , printing the file name and pid. Below are the results for two processes (GPUs).
   
  Process 2070861:
  pid and filename:  2070861 /home/mlperf_data/unet3d_500/train/img_329_of_500.npz 1
  pid and filename:  2070861 /home/mlperf_data/unet3d_500/train/img_475_of_500.npz 1
  pid and filename:  2070861 /home/mlperf_data/unet3d_500/train/img_382_of_500.npz 1
  pid and filename:  2070861 /home/mlperf_data/unet3d_500/train/img_157_of_500.npz 1
  pid and filename:  2070861 /home/mlperf_data/unet3d_500/train/img_367_of_500.npz 2
  pid and filename:  2070861 /home/mlperf_data/unet3d_500/train/img_418_of_500.npz 2
  pid and filename:  2070861 /home/mlperf_data/unet3d_500/train/img_232_of_500.npz 2
  pid and filename:  2070861 /home/mlperf_data/unet3d_500/train/img_354_of_500.npz 2
  pid and filename:  2070861 /home/mlperf_data/unet3d_500/train/img_074_of_500.npz 3
  pid and filename:  2070861 /home/mlperf_data/unet3d_500/train/img_338_of_500.npz 3
  pid and filename:  2070861 /home/mlperf_data/unet3d_500/train/img_468_of_500.npz 3
  pid and filename:  2070861 /home/mlperf_data/unet3d_500/train/img_458_of_500.npz 3

  Process 2070579:
  pid and filename: 2070579 /home/mlperf_data/unet3d_500/train/img_329_of_500.npz 1
  pid and filename:  2070579 /home/mlperf_data/unet3d_500/train/img_475_of_500.npz 1
  pid and filename:  2070579 /home/mlperf_data/unet3d_500/train/img_382_of_500.npz 1
  pid and filename:  2070579 /home/mlperf_data/unet3d_500/train/img_157_of_500.npz 1
  pid and filename:  2070579 /home/mlperf_data/unet3d_500/train/img_367_of_500.npz 2
  pid and filename:  2070579 /home/mlperf_data/unet3d_500/train/img_418_of_500.npz 2
  pid and filename:  2070579 /home/mlperf_data/unet3d_500/train/img_232_of_500.npz 2
  pid and filename:  2070579 /home/mlperf_data/unet3d_500/train/img_354_of_500.npz 2
  pid and filename:  2070579 /home/mlperf_data/unet3d_500/train/img_074_of_500.npz 3
  pid and filename:  2070579 /home/mlperf_data/unet3d_500/train/img_338_of_500.npz 3
  pid and filename:  2070579 /home/mlperf_data/unet3d_500/train/img_468_of_500.npz 3
  pid and filename:  2070579 /home/mlperf_data/unet3d_500/train/img_458_of_500.npz 3

The above results show that different GPUs have accessed the same part of the dataset, which should ideally be non-overlapping for different datasets. Should we consider using my_rank and comm_size to split the dataset when generating dataloader in dlio_benchmark/dlio_benchmark/data_loader/torch_data_loader.py?

**Comment by zhenghh04** [comment]
@yxkyong Thank you. I confirmed the observation. We will fix that. 

@hariharan-devarajan Could you take a look? This has to do with the build sample index

**Comment by yxkyong** [comment]
@zhenghh04 Thank you. Will the dilo benchmark branch in mlperf storage v1.0 continue to use 99d3fb0 or another branch?

**Comment by zhenghh04** [comment]
@yxkyong could you check whether this PR#166 fixes the issue?

**Comment by yxkyong** [comment]
> @yxkyong could you check whether this PR #166 fixes the issue?

Thank you for addressing the issue! I just checked the latest update, my problem has been resolved.  We've encountered an issue with the global index map. Could you take a look issue: https://github.com/argonne-lcf/dlio_benchmark/issues/167?

**Comment by zhenghh04** [comment]
Closing this issue now. The other issue is addressed with another PR as mentioned.
