### ISSUE TITLE
global index map repeated insertion

### ISSUE THREAD

**Issue by yxkyong** [argonne-lcf/dlio_benchmark#167]
Hey Team,
We find global index map repeated insertion while testing the MLPerf Benchmark v1.0.
- Our environment
   mlperf storage v1.0-branch (https://github.com/mlcommons/storage/tree/v1.0-branch )
   dlio_benchmark@main(c410121) (https://github.com/argonne-lcf/dlio_benchmark)
   test command:
   `./benchmark.sh run --hosts x.x.x.x --workload unet3d --accelerator-type h100 --num-accelerators 10 --results-dir /result --param dataset.num_files_train=500 --param dataset.data_folder=/data 
`
- Result
   We find that function get_global_map_index in [dlio_benchmark/utils/config.py](https://github.com/argonne-lcf/dlio_benchmark/blob/main/dlio_benchmark/utils/config.py) repeatedly inserts the first elements in the construction of the global index map, which leads to the following global index map result:

    {0: ('img_000_of_500.npz', 0), 
    1: ('img_000_of_500.npz', 0), 
    2: ('img_001_of_500.npz', 0), 
    3: ('img_002_of_500.npz', 0), 
    ...
     499: ('img_498_of_500.npz', 0)}

   img_000_of_500.npz is inserted twice, and img_499_of_500.npz cannot be inserted, which may cause an index error.

**Comment by zhenghh04** [comment]
@yxkyong Please check the fix: https://github.com/argonne-lcf/dlio_benchmark/pull/168. 

I'll merge it to the main branch after passing the tests.

**Comment by yxkyong** [comment]
> @yxkyong Please check the fix: #168.
> 
> I'll merge it to the main branch after passing the tests.

Thank you. It fixes the global index map issue.

**Comment by yxkyong** [comment]
@zhenghh04  https://github.com/argonne-lcf/dlio_benchmark/pull/168 fixed this issue.
