### ISSUE TITLE
redundant shuffle in dali dataloader

### ISSUE THREAD

**Issue by yxkyong** [argonne-lcf/dlio_benchmark#170]
Hey team,

- During the cosmoflow workload test, we found the following phenomenon:

  When the dali dataloader invokes the read operation, redundant shuffle is performed on indices. 
  `./benchmark.sh run --hosts x.x.x.x --workload cosmoflow --accelerator-type h100 --num-accelerators 1 --results-dir /result --param dataset.num_files_train=500 --param dataset.data_folder=/data`
  (set GPU_num and read_thread num to 1 )

- Result
  As shown below, we recorded filename accesses to files and shuffle operations that occurred. This indicates that after the first three file accesses, additional shuffle operations occurred. Subsequent access lists are reasonable, we are not sure of the reason for this.
[INFO] Shuffle operation happened.
[INFO] Pid and Filename and Step:  229 1685966 img_229_of_500.tfrecord 0
[INFO] Pid and Filename and Step:  337 1685966 img_337_of_500.tfrecord 1
[INFO] Pid and Filename and Step:  327 1685966 img_327_of_500.tfrecord 2
[INFO] Shuffle operation happened.
[INFO] Pid and Filename and Step:  454 1685975 img_454_of_500.tfrecord 0
[INFO] Pid and Filename and Step:  379 1685975 img_379_of_500.tfrecord 1
[INFO] Pid and Filename and Step:  395 1685975 img_395_of_500.tfrecord 2
[INFO] Pid and Filename and Step:  43 1685975 img_043_of_500.tfrecord 3
[INFO] Pid and Filename and Step:  283 1685975 img_283_of_500.tfrecord 4
[INFO] Pid and Filename and Step:  383 1685975 img_383_of_500.tfrecord 5
[INFO] Pid and Filename and Step:  131 1685975 img_131_of_500.tfrecord 6
[INFO] Pid and Filename and Step:  447 1685975 img_447_of_500.tfrecord 7
[INFO] Pid and Filename and Step:  205 1685975 img_205_of_500.tfrecord 8
...

**Comment by yxkyong** [comment]
@zhenghh04  We found the cause of this problem, because the run function in [main.py](https://github.com/argonne-lcf/dlio_benchmark/blob/main/dlio_benchmark/main.py) initialized the loader called [loader.read () ](https://github.com/argonne-lcf/dlio_benchmark/blob/c410121b6811141ac64b14abf50e316520a199ba/dlio_benchmark/main.py#L338)once, and [loader.next ()](https://github.com/argonne-lcf/dlio_benchmark/blob/c410121b6811141ac64b14abf50e316520a199ba/dlio_benchmark/main.py#L263C1-L263C22) will be called again in the _train function. For the dali loader,[ read ()](https://github.com/argonne-lcf/dlio_benchmark/blob/c410121b6811141ac64b14abf50e316520a199ba/dlio_benchmark/data_loader/dali_data_loader.py#L84) was called twice. Two shuffles are performed before the first epoch starts. This problem only occurs in the dali workload because the [read ()](https://github.com/argonne-lcf/dlio_benchmark/blob/c410121b6811141ac64b14abf50e316520a199ba/dlio_benchmark/data_loader/dali_data_loader.py#L128) function in the next () function of the dali dataloader need to reset the data loader.  Could you please take a look at this issue? We can also help submit a PR to fix it.

**Comment by zhenghh04** [comment]
@yxkyong I push a new change in #168 which should fix this issue

**Comment by yxkyong** [comment]
> @yxkyong I push a new change in #168 which should fix this issue

Yes! The issue is fixed.
