### ISSUE TITLE
Error process in the installation of dlio_benchmark requirement about MLPerf Storage v1.0

### ISSUE THREAD

**Issue by ByoungjunSeo** [argonne-lcf/dlio_benchmark#171]
I got a failed building wheel for dlio_profiler_py in following up requirements.txt file.
I already installed mpich from yum.

You can see the error log in attached error log file.

My environment is like below.

- OS version: CentOS Stream 8
- Python version: 3.10.12
- Pip version: 23.2, 24.0

Please let me know what is matter.
If you want to more about my environment, I can let you know.

Thanks
[pip23.2 installation error log.txt](https://github.com/argonne-lcf/dlio_benchmark/files/14595156/pip23.2.installation.error.log.txt)
[dlio_requirements.txt](https://github.com/argonne-lcf/dlio_benchmark/files/14595175/dlio_requirements.txt)
[pip24 installation error log.txt](https://github.com/argonne-lcf/dlio_benchmark/files/14595174/pip24.installation.error.log.txt)

**Comment by hariharan-devarajan** [comment]
Based on your log I see

/usr/local/lib/python3.10/site-packages/dlio_profiler/include/../include/cpp-logger/logger.h":
        Permission denied.


U may need a sudo but pip doesn't recommend installing in system space.
Ideally, I would recommend using a virtual env to do all this in user space.


Best
Hari

**Comment by ByoungjunSeo** [comment]
Thanks for letting me know.
But I have same problem even if I was in virtual env from Python 3.10.
Attached note file is my error log what I was doing.
[code error.txt](https://github.com/argonne-lcf/dlio_benchmark/files/14766755/code.error.txt)

**Comment by ByoungjunSeo** [comment]
I solved this problem with installing hwloc-devel and hwloc-libs in host system.

and then it is working installation dlio_benchmark from conda python virtual environment.

Thanks!
