### ISSUE TITLE
Is it possible to select a specific disk on which to run the benchmark?

### ISSUE THREAD

**Issue by shp776** [argonne-lcf/dlio_benchmark#175]
Hi, I have some questions.

I want to run the benchmark on an nvme disk that is not mounted on the file system.
However, it seems that when I install the tool, it is installed in the /home directory of the ssd where my OS is installed, and it appears to operate by generating benchmark data (u-net 3d) in this location.
If I want to run the benchmark and measure performance on the nvme disk I want to test, do I need to mount the nvme disk to the file system and install the tool in that location? (i.e I want to check if this evaluation is conducted in a logical test(file system mount) environment, not a physical test)

I'll be waiting for your answer.
Thank you.

**Comment by crtierney** [comment]
I would just create a link to the directory on your nvme disk.

**Comment by zhenghh04** [comment]
The code can be in the /home directory. But you'll have to modify the `++workload.dataset.data_folder` to specify where to put the dataset.
