### ISSUE TITLE
The samples of tfrecord in dali dataloader are not actually read from storage

### ISSUE THREAD

**Issue by yxkyong** [argonne-lcf/dlio_benchmark#177]
- Environment:
   MLperf v1.0 (https://github.com/mlcommons/storage/tree/v1.0-branch)
   dlio_benchmark https://github.com/argonne-lcf/dlio_benchmark/commit/8d57e14012150ad507ff371a3345760b27576189

- Problem: 
 While testing the latest versions of resnet50 and cosmoflow workload, we find that the tfrecord files in the storage system are not actually read.  We try to locate the problem and find that the functions for parsing TFRecord, such as _parse_image in tf_reader.py, were not invoked during the benchmark running. 

- Result:
As a result, during the test of the storage system, the workloads resnet50 and cosmoflow that use the dali dataloader to read TFRecords do not actually interact with the storage system.

**Comment by yxkyong** [comment]
@zhenghh04  Could you please take a look and check the issue?

**Comment by crtierney** [comment]
I am seeing the same issue.  Switching to native_dali allowed the reads to happen, but I haven't debugged the change to see if there aren't more issues.

**Comment by zhenghh04** [comment]
Yes, I'll take a look and update to you.

**Comment by zhenghh04** [comment]
@yxkyong and @crtierney: I confirmed this issue. Working on a way to address this. Will update here later.

**Comment by hariharan-devarajan** [comment]
@zhenghh04 This means the TFRecord pipeline is not getting executed correctly. As I understand, TFRecord would need tensorflow to run. I think this will not work with Pytorch or Dali. We will have to have a Tfrecord reader with protobuf to do this. If u wanna run tfrecord with pytorch u need to use the native dali data loader.

**Comment by yxkyong** [comment]
@zhenghh04 @hariharan-devarajan    In my experience, tfrecord can be loaded and used properly in pytorch.  Currently, the  [_parse_image function](https://github.com/argonne-lcf/dlio_benchmark/blob/8d57e14012150ad507ff371a3345760b27576189/dlio_benchmark/reader/tf_reader.py#L58) and the [next function](https://github.com/argonne-lcf/dlio_benchmark/blob/8d57e14012150ad507ff371a3345760b27576189/dlio_benchmark/reader/tf_reader.py#L82) can correctly parse samples in the TFRecord, but they are not called in implementation of [read_index ](https://github.com/argonne-lcf/dlio_benchmark/blob/8d57e14012150ad507ff371a3345760b27576189/dlio_benchmark/reader/tf_reader.py#L101), [dali dataloader](https://github.com/argonne-lcf/dlio_benchmark/blob/8d57e14012150ad507ff371a3345760b27576189/dlio_benchmark/data_loader/dali_data_loader.py#L73) and [dali dataset](https://github.com/argonne-lcf/dlio_benchmark/blob/8d57e14012150ad507ff371a3345760b27576189/dlio_benchmark/data_loader/dali_data_loader.py#L34). I think maybe you can combine the two to implement a tfrecord dataloader directly for pytorch.

**Comment by zhenghh04** [comment]
Yes, it can be. I am working on a proper way. Should be able to finish the fix later this week.

**Comment by LouisDDN** [comment]
Hi, any update on this? AFAIK this is blocking for cosmo & resnet50 for MLPerfStorage v1.0.

**Comment by yxkyong** [comment]
@zhenghh04  I see your new commits and I am wondering if this issue was fixed. Will ResNet50 and CosmoFlow use the PyTorch framework, TensorFlow, or DALI?

**Comment by zhenghh04** [comment]
@yxkyong we fixed the resnet50 and cosmoflow issue with the most recent commit. Please check it out.
