### ISSUE TITLE
Supporting dataset spread into multiple folders

### ISSUE THREAD

**Issue by zhenghh04** [argonne-lcf/dlio_benchmark#2]
We would like to add support for spreading the dataset into different folders instead of assuming all of them in the same folder, as suggested by one of our users.

**Comment by sajikvr** [comment]
@zhenghh04  As discussed, it would be better to divide the files onto different directories at a single level as well as to limit the max number of files per directory, may be a few hundred max.

**Comment by zhenghh04** [comment]
@sajikvr I just added the support. 

One can specify the number of subfolders used to store the dataset. 

++dataset.num_subfolders_train and ++dataset.num_subfolders_eval will do the work (in hydra config framework)

I am closing this issue now.
