### ISSUE TITLE
Post processing issue , ImportError: cannot import name 'quantiles'

### ISSUE THREAD

**Issue by karanveersingh5623** [argonne-lcf/dlio_benchmark#27]
Hi Team , trying to create report from profilers trace , its failing on importing quantiles from statistics module .

```
[root@k8s-worker86 dlio_benchmark]# ll
total 40
drwxr-xr-x  4 root root    54 Dec 15 12:18 configs
-rw-r--r--  1 root root   372 Dec 13 10:48 Dockerfile
drwxr-xr-x  3 root root    69 Dec 13 10:48 docs
-rwxr-xr-x  1 root root     0 Dec 15 12:20 __init__.py
-rw-r--r--  1 root root 11357 Dec 13 10:48 LICENSE
-rw-r--r--  1 root root  8459 Dec 13 10:48 README.md
-rw-r--r--  1 root root  1028 Dec 13 10:48 requirements.txt
-rw-r--r--  1 root root   613 Dec 13 10:48 setup.cfg
-rw-r--r--  1 root root   215 Dec 13 10:48 setup.py
drwxr-xr-x 11 root root   228 Dec 15 12:23 src
drwxr-xr-x  3 root root   106 Dec 13 10:48 tests
[root@k8s-worker86 dlio_benchmark]#
[root@k8s-worker86 dlio_benchmark]#
[root@k8s-worker86 dlio_benchmark]# python3 -m src.dlio_postprocessor.py --output-folder /mnt/dlio/hydra_log/default/2022-12-15-02-27-09
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/root/dlio_benchmark/src/dlio_postprocessor.py", line 24, in <module>
    from statistics import mean, median, stdev, quantiles
ImportError: cannot import name 'quantiles'
[root@k8s-worker86 dlio_benchmark]#
[root@k8s-worker86 dlio_benchmark]#
[root@k8s-worker86 dlio_benchmark]#
[root@k8s-worker86 dlio_benchmark]# pip install statistics
Requirement already satisfied: statistics in /usr/local/lib/python3.6/site-packages (1.0.3.5)
Requirement already satisfied: docutils>=0.3 in /usr/local/lib/python3.6/site-packages (from statistics) (0.18.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

**Comment by zhenghh04** [comment]
@karanveersingh5623 

Please try the following command: 

`python3 src/dlio_postprocessor.py --output-folder /mnt/dlio/hydra_log/default/2022-12-15-02-27-09`

**Comment by karanveersingh5623** [comment]
@zhenghh04 , I made __init__.py files in all sub folders of src , still getting the error 

```
[root@k8s-worker86 dlio_benchmark]# ll src/
total 44
drwxr-xr-x 3 root root   114 Dec 16 10:57 common
drwxr-xr-x 2 root root   160 Dec 13 10:48 computation
drwxr-xr-x 2 root root   204 Dec 13 10:48 data_generator
-rw-r--r-- 1 root root 15330 Dec 13 10:48 dlio_benchmark.py
-rwxr-xr-x 1 root root 28616 Dec 13 10:48 dlio_postprocessor.py
drwxr-xr-x 2 root root   103 Dec 13 10:48 framework
-rwxr-xr-x 1 root root     0 Dec 15 12:21 __init__.py
drwxr-xr-x 2 root root   152 Dec 13 10:48 profiler
drwxr-xr-x 3 root root   249 Dec 13 10:48 reader
drwxr-xr-x 2 root root   102 Dec 13 10:48 storage
drwxr-xr-x 3 root root   102 Dec 16 10:57 utils
[root@k8s-worker86 dlio_benchmark]#
[root@k8s-worker86 dlio_benchmark]#
[root@k8s-worker86 dlio_benchmark]#
[root@k8s-worker86 dlio_benchmark]# python3 src/dlio_postprocessor.py --output-folder /mnt/dlio/hydra_log/default/2022-12-15-02-27-09
Traceback (most recent call last):
  File "src/dlio_postprocessor.py", line 23, in <module>
    from src.utils.utility import str2bool
ModuleNotFoundError: No module named 'src'
```

**Comment by zhenghh04** [comment]
@karanveersingh5623 Did you set `PYTHONPATH=/mnt/dlio:$PYTHONPATH`

**Comment by karanveersingh5623** [comment]
@zhenghh04 ....failing at same quantiles error ...something is missing .

```
[root@k8s-worker86 dlio_benchmark]# export PYTHONPATH=/mnt/dlio:$PYTHONPATH
[root@k8s-worker86 dlio_benchmark]# python3 src/dlio_postprocessor.py --output-folder /mnt/dlio/hydra_log/default/2022-12-15-02-27-09
Traceback (most recent call last):
  File "src/dlio_postprocessor.py", line 24, in <module>
    from statistics import mean, median, stdev, quantiles
ImportError: cannot import name 'quantiles'
```

**Comment by zhenghh04** [comment]
looks that the statistics module is too old. Please try upgrading the module.

**Comment by karanveersingh5623** [comment]
I guess its already at latest version

```
[root@k8s-worker86 dlio_benchmark]# pip install statistics -U
Requirement already satisfied: statistics in /usr/local/lib/python3.6/site-packages (1.0.3.5)
Requirement already satisfied: docutils>=0.3 in /usr/local/lib/python3.6/site-packages (from statistics) (0.18.1)
```

**Comment by zhenghh04** [comment]
Python 3.6.8 statistics module does not have quantiles. 

You can try newer version (it would be easier to run it within docker)

[huihuo.zheng@zion ~]$ docker run -it python:3.6.8
Python 3.6.8 (default, Jun 19 2019, 01:57:54) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import statistics
>>> help(statistics)
Help on module statistics:

NAME
    statistics - Basic statistics module.

MODULE REFERENCE
    https://docs.python.org/3.6/library/statistics
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides functions for calculating statistics of data, including
    averages, variance, and standard deviation.
    
    Calculating averages
    --------------------
    
    ==================  =============================================
    Function            Description
    ==================  =============================================
    mean                Arithmetic mean (average) of data.
    harmonic_mean       Harmonic mean of data.
    median              Median (middle value) of data.
    median_low          Low median of data.
    median_high         High median of data.
    median_grouped      Median, or 50th percentile, of grouped data.
    mode                Mode (most common value) of data.
    ==================  =============================================

**Comment by karanveersingh5623** [comment]
@zhenghh04 ...thanks .....docker python version works :)

**Comment by zhenghh04** [comment]
Great! I'll close the issue now.
