### ISSUE TITLE
Output explanation?

### ISSUE THREAD

**Issue by laytonjbgmail** [argonne-lcf/dlio_benchmark#38]
I just started testing DLIO and the output has me confused. Is there an explanation of the output somewhere?

Thanks!

**Comment by zhenghh04** [comment]
@laytonjbgmail We don't have it yet. Could you explain which part made you confused?

**Comment by laytonjbgmail** [comment]
I'll start with a few questions and then add others if that's OK.

1. In the output is the primary measure of performance Samples/s? If we know the sample size, we can then convert this to bytes/s (or other units) - correct?

2. Does the output sum the results from all MPI ranks?

3. Is the checkpoint I/O included with the epoch output of Samples/s? Or is it separate?

Thank you!

Jeff

**Comment by zhenghh04** [comment]
Hi Jeff, 

We recently updated the report in the mlperf_storage_v0.5.1 branch (will also be merged to the main branch soon). We reported samples per second; and the bytes / second is also estimated by samples/second * record_size. The output in the log sum up the results from all the MPI ranks. 

The checkpoint I/O is not included the output of Samples / second.
