### ISSUE TITLE
Unable to run, missing package perftrace

### ISSUE THREAD

**Issue by crtierney** [argonne-lcf/dlio_benchmark#45]
Did the code get updated but not the requirements.txt file?  I started getting the following error when I updated to the latest head (at about 1pm MT 3/10).

ImportError: cannot import name 'perftrace' from 'src.utils.utility' (/workspace/dlio/src/utils/utility.py)
    from src.utils.utility import utcnow, measure_performance, perftrace

I am searching if there is a pip package associated to this, but I haven't found it yet.

**Comment by zhenghh04** [comment]
@crtierney please try the mlperf_storage_v0.5 branch instead

We are in the process of fixing the main branch. Sorry for the inconvenience.

**Comment by zhenghh04** [comment]
This should be addressed even in the current main branch.
