### ISSUE TITLE
Plugin design of DLIO Benchmark for adding custom data readers.

### ISSUE THREAD

**Issue by hariharan-devarajan** [argonne-lcf/dlio_benchmark#70]
I was wondering how could data management research such as DYAD, Hermes, or Stimulus add their own data readers or data loader implementations without our library.

I think python plugins can help us build that. It is well suited for our factory design already. 

[Documentation on python plugins](https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/)

**Comment by zhenghh04** [comment]
This is great to have it!
