### ISSUE TITLE
Darshan Tool

### ISSUE THREAD

**Issue by shubh0155** [argonne-lcf/dlio_benchmark#86]
Hi i am trying to run cosmoflow dlio benchmark and i came across the darshan profiling tool. Can anyone help me out to how to use the darshan profiler to generate the reports and graphs which it generates. what steps to be followed and what commands to be usued on linux system

**Comment by zhenghh04** [comment]
Hi @shubh0155 , currently darshan has to be run outside of DLIO. 
So what you can do is set LD_PRELOAD=PATH_TO_DARSHAN/libdarshan.so, then run DLIO. This will generate the darshan trace in the similar way as it does to an HPC application.
